### PR TITLE
Added missing new object HeaderFlags.

### PR DESCRIPTION
**Pull request by brlbil**
Modified String() function. I have used the same string format as I have seen Flags printed in the strace output. Could not come up with a better one.

I have used missing Flags in a project, I could simply define them in there but I believe they belong in this package.

### CODE REVIEW

**Comment by mdlayher** [comment]
Seems reasonable, but I will do an in-depth review tomorrow. Out of curiosity, what's your project? Would like to see the source!

**Comment by brlbil** [comment]
I am working on github.com/jsimonetti/rtnetlink which I will later use for a project, which is on the drawing board at this point. I have added RouteSerive to rtnetlink and also made some changes which are not ready to push yet. I would like to add missing tests but I could not get around to do it yet.

As an example of usage, in rtnetlink AddressService New function only netlink.HeaderFlagsRequest flag is used, this seems to be wrong needs to replaced with netlink.HeaderFlagsRequest | headerFlagCreate | netlink.HeaderFlagsAcknowledge | headerFlagExcl. Obviously, headerFlagCreate and headerFlagExcl are private variables at this point.

**Comment by mdlayher** [comment]
LGTM!

**Comment by mdlayher** [comment]
Looking forward to checking out your project!

**Pull request merged**
